name: "Build Zenoh Recipes"
description: "Build steps for Zenoh recipes using kas"

inputs:
  shared_memory:
    description: "Shared memory option"
    required: true
  zenoh_cpp_backend:
    description: "Zenoh C++ backend option"
    required: true

runs:
  using: composite
  steps:
    - name: Install kas
      id: kas
      shell: bash
      run: |
        wget https://github.com/siemens/kas/raw/5.0/kas-container -O /tmp/kas
        chmod +x /tmp/kas
        echo "KAS=/tmp/kas" >> "${GITHUB_OUTPUT}"

    - name: Select kas config
      id: config
      shell: bash
      run: |
        if [ "${{ matrix.shared_memory }}" = "shm" ]; then
          SHM=":kas/shared-memory.yml:kas/unstable-api.yml"
        fi
        if [[ "${{ matrix.zenoh_cpp_backend }}" =~ ^(zenoh-c|both)$ ]]; then
          BE=":kas/zenoh-c-backend.yml"
        fi
        if [[ "${{ matrix.zenoh_cpp_backend }}" =~ ^(zenoh-pico|both)$ ]]; then
          BE="${BE}:kas/zenoh-pico-backend.yml"
        fi
        echo "KAS_CONFIG=kas/ci.yml${SHM}${BE}" >> "${GITHUB_OUTPUT}"

    - name: Checkout with kas
      shell: bash
      run: |
        # This needed to trigger necessary dependencies installation before maximizing build space
        ${{ steps.kas.outputs.KAS }} checkout ${{ steps.config.outputs.KAS_CONFIG }}

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        build-mount-path: "${GITHUB_WORKSPACE}/build"
        root-reserve-mb: 10240
        swap-size-mb: 2048
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"

    - name: Cache Yocto downloads
      uses: actions/cache@v4
      with:
        path: |
          build/downloads
        key: yocto-downloads-${{ hashFiles('kas/*.yml') }}-${{ github.run_id }}
        restore-keys: |
          yocto-downloads-${{ hashFiles('kas/*.yml') }}-
          yocto-downloads-

    - name: Cache Yocto sstate
      uses: actions/cache@v4
      with:
        path: |
          build/sstate-cache
        key: yocto-sstate-${{ matrix.shared_memory }}-${{ matrix.zenoh_cpp_backend }}-${{ hashFiles('**/kas*.yml') }}
        restore-keys: |
          yocto-sstate-${{ matrix.shared_memory }}-${{ matrix.zenoh_cpp_backend }}-
          yocto-sstate-

    - name: Build with kas
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build ${{ steps.config.outputs.KAS_CONFIG }}

    - name: List built RPMs and native components
      shell: bash
      run: |
        find build/tmp/deploy/rpm/core2_64 \
          -name '*zenoh*.rpm' \
          -exec echo -e "\n=== {} ===" \; \
          -exec rpm -qp --queryformat "[%-20{=NAME} %{FILENAMES}\n]" {} \;

        find build/tmp/sysroots-components/x86_64 \
          -depth -maxdepth 1 \
          -name 'zenoh*-native' \
          -exec echo -e "\n=== {} ===" \; \
          -exec tree -I sysroot-providers {} \;
