name: "Build Zenoh Recipes"
description: "Build all Zenoh recipes using kas (shm enabled, both backends)"

inputs:
  force_rebuild:
    description: "Force full rebuild (ignore cache)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install kas
      id: kas
      shell: bash
      run: |
        wget -q https://github.com/siemens/kas/raw/5.0/kas-container -O /tmp/kas
        chmod +x /tmp/kas
        echo "KAS=/tmp/kas" >> "${GITHUB_OUTPUT}"

    - name: Checkout with kas
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} checkout kas/ci.yml:kas/shared-memory.yml:kas/unstable-api.yml

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        build-mount-path: "${{ github.workspace }}/build"
        root-reserve-mb: 10240
        swap-size-mb: 2048
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"

    - name: Restore sstate cache
      if: ${{ inputs.force_rebuild != 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: build/sstate-cache
        key: yocto-sstate-${{ github.ref_name }}-${{ hashFiles('kas/ci.lock.yml') }}
        restore-keys: |
          yocto-sstate-${{ github.ref_name }}-
          yocto-sstate-master-

    - name: Restore downloads cache
      uses: actions/cache/restore@v4
      with:
        path: build/downloads
        key: yocto-downloads-${{ hashFiles('kas/*.yml', 'meta-zenoh/**/*.bb', 'meta-zenoh/**/*.inc') }}
        restore-keys: |
          yocto-downloads-

    - name: Build zenoh and zenoh-c (Rust backend)
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build kas/ci.yml:kas/shared-memory.yml:kas/unstable-api.yml -- zenoh zenoh-c

    - name: Build zenoh-pico
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build kas/ci.yml:kas/shared-memory.yml:kas/unstable-api.yml -- zenoh-pico

    - name: Build zenoh-cpp with zenoh-c backend
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build kas/ci.yml:kas/shared-memory.yml:kas/unstable-api.yml:kas/zenoh-c-backend.yml -- zenoh-cpp

    - name: Build zenoh-cpp with zenoh-pico backend
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build kas/ci.yml:kas/shared-memory.yml:kas/unstable-api.yml:kas/zenoh-pico-backend.yml -- zenoh-cpp

    - name: Clean sstate duplicates
      shell: bash
      run: |
        SSTATE_SCRIPT="layers/oe-core/scripts/sstate-cache-management.py"
        if [ -f "${SSTATE_SCRIPT}" ]; then
          echo "Cleaning sstate duplicates..."
          python3 "${SSTATE_SCRIPT}" --remove-duplicated --cache-dir=build/sstate-cache -y || true
        fi

    - name: Save sstate cache
      uses: actions/cache/save@v4
      with:
        path: build/sstate-cache
        key: yocto-sstate-${{ github.ref_name }}-${{ hashFiles('kas/ci.lock.yml') }}

    - name: Save downloads cache
      uses: actions/cache/save@v4
      with:
        path: build/downloads
        key: yocto-downloads-${{ hashFiles('kas/*.yml', 'meta-zenoh/**/*.bb', 'meta-zenoh/**/*.inc') }}

    - name: List built RPMs and native components
      shell: bash
      run: |
        echo "=== Built RPM packages ==="
        find build/tmp/deploy/rpm -name '*zenoh*.rpm' \
          -exec echo -e "\n=== {} ===" \; \
          -exec rpm -qp --queryformat "[%-20{=NAME} %{FILENAMES}\n]" {} \; 2>/dev/null || echo "No RPMs found"

        echo -e "\n=== Native sysroot components ==="
        find build/tmp/sysroots-components/x86_64 \
          -maxdepth 1 -type d -name 'zenoh*-native' \
          -exec echo -e "\n=== {} ===" \; \
          -exec tree -L 2 -I sysroot-providers {} \; 2>/dev/null || echo "No native components found"
