name: "Build Zenoh Recipes"
description: "Build steps for Zenoh recipes using kas"

inputs:
  shared_memory:
    description: "Shared memory option"
    required: true
  zenoh_cpp_backend:
    description: "Zenoh C++ backend option"
    required: true

runs:
  using: composite
  steps:
    - name: Install kas
      id: kas
      shell: bash
      run: |
        wget https://github.com/siemens/kas/raw/4.8.1/kas-container -O /tmp/kas
        chmod +x /tmp/kas
        echo "KAS=/tmp/kas" >> "${GITHUB_OUTPUT}"

    - name: Select kas config
      id: config
      shell: bash
      run: |
        if [ "${{ matrix.shared_memory }}" = "shm" ]; then
          SHM=":kas/shared-memory.yml:kas/unstable-api.yml"
        fi
        if [[ "${{ matrix.zenoh_cpp_backend }}" =~ ^(zenoh-c|both)$ ]]; then
          BE=":kas/zenoh-c-backend.yml"
        fi
        if [[ "${{ matrix.zenoh_cpp_backend }}" =~ ^(zenoh-pico|both)$ ]]; then
          BE="${BE}:kas/zenoh-pico-backend.yml"
        fi
        echo "KAS_CONFIG=kas/ci.yml${SHM}${BE}" >> "${GITHUB_OUTPUT}"

    - name: Build with kas
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build ${{ steps.config.outputs.KAS_CONFIG }}

    - name: List built RPMs and native components
      shell: bash
      run: |
        find build/tmp/deploy/rpm/core2_64 \
          -name '*zenoh*.rpm' \
          -exec echo -e "\n=== {} ===" \; \
          -exec rpm -qp --queryformat "[%-20{=NAME} %{FILENAMES}\n]" {} \;

        find build/tmp/sysroots-components/x86_64 \
          -depth -maxdepth 1 \
          -name 'zenoh*-native' \
          -exec echo -e "\n=== {} ===" \; \
          -exec tree -I sysroot-providers {} \;
